### ISSUE TITLE
Documentation team need an easy way to edit markdown content

### ISSUE THREAD

**Issue by sire-sam** [sire-sam/ss.study.fractal-build#1]
To avoid a bottleneck at "front-end" team, it would be great if other members could edit or add definition in style-guide.

At first, "markdown" syntax does not seems to be seen as an "easy to use" syntax. 
So we could try to find an app to edit markdown.

## Todo
- [ ] find and propose an app for markdown edition
- [ ] define and propose a workflow to update markdown in git repo
- [ ] find a tool to easily manage a git repo for "non-developers" profile
